server:
  port: 10010

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/testdb
    username: postgres
    password: ttt20000608
    driver-class-name: org.postgresql.Driver


