server:
  port: 10010

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: ttt20000608
  datasource:
    url: jdbc:postgresql://49.234.45.25:5432/testuser
    username: postgres
    password: ttt20000608.
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    username: loveT
    password: ttt20000608
    port: 5672
    host: 192.168.31.128
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


