server:
  port: 10010

spring:
  datasource:
    url: jdbc:postgresql://49.234.45.25:5432/testuser
    username: postgres
    password: ttt20000608.
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    username: root
    password: pinkitec!
    port: 5672
    host: mq.server.url
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


